name: auto-update

on:
  schedule:
    - cron: "0 0 * * *"
  push: {}
  workflow_dispatch: {}

permissions:
  contents: write
  id-token: write

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Pip install
        run: pip install -r requirements.txt
      - name: Parse JPX all stock list
        run: python parse_jpx_all_stock_list.py
      - name: Parse JPX new stock list
        run: python parse_jpx_new_stock_list.py
      - name: Parse Kessan list
        run: python parse_kessan_list.py
      - name: Parse JPX new ETF list
        run: python parse_jpx_new_etf_list.py
      - name: Merge symbols
        run: python merge_symbols.py
      - name: Configure AWS Credentials for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4
        with:
          mask-aws-account-id: true
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/kabu-json-github-actions-role
          role-session-name: github-actions-${{ github.job }}-${{ github.run_id }}-${{ github.run_number }}
      - name: Upload to S3
        run: |
          aws s3 cp all_stocks.json s3://kabu-json-public-static-data-bucket/kabu-json-all-stock-list/v1/all_stocks.json --content-type application/json
          aws s3 cp new_listings.json s3://kabu-json-public-static-data-bucket/kabu-json-all-stock-list/v1/new_listings.json --content-type application/json
          aws s3 cp monthly.json s3://kabu-json-public-static-data-bucket/kabu-json-all-stock-list/v1/monthly.json --content-type application/json
      - name: Commit to keep workflow running
        run: |
          git config user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f all_stocks.json
          git commit -m "Update json file $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push || echo "No changes to commit"
